# Generated by Django 2.2.13 on 2021-02-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210227_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Book'),
        ),
    ]
