# Generated by Django 2.2.13 on 2021-03-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210227_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('M', 'Методические указания'), ('H', 'Художественная литература'), ('A', 'Книги на английском')], max_length=2),
        ),
    ]
