# Generated by Django 2.2.13 on 2021-03-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210309_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('E', 'Английский'), ('R', 'Русский'), ('B', 'Белорусский')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='inventory_number',
            field=models.CharField(default=12345, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('S', 'Методические указания'), ('H', 'Художественная литература'), ('T', 'Техническая литература')], max_length=2),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='core.Author'),
        ),
    ]
