# Generated by Django 2.2.13 on 2021-03-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210311_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='inventory_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
